# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: devices.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'devices.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdevices.proto\x12\x07\x64\x65vices\"\x13\n\x11GetDevicesRequest\"7\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bmac_address\x18\x03 \x01(\t\"6\n\x12GetDevicesResponse\x12 \n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0f.devices.Device2Y\n\rDeviceService\x12H\n\rGetAllDevices\x12\x1a.devices.GetDevicesRequest\x1a\x1b.devices.GetDevicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'devices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDEVICESREQUEST']._serialized_start=26
  _globals['_GETDEVICESREQUEST']._serialized_end=45
  _globals['_DEVICE']._serialized_start=47
  _globals['_DEVICE']._serialized_end=102
  _globals['_GETDEVICESRESPONSE']._serialized_start=104
  _globals['_GETDEVICESRESPONSE']._serialized_end=158
  _globals['_DEVICESERVICE']._serialized_start=160
  _globals['_DEVICESERVICE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
