# Generated by Django 5.1.2 on 2025-02-15 18:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Relative humidity in percentage')),
                ('pressure', models.FloatField(help_text='Atmospheric pressure in hPa')),
                ('soil_moisture', models.IntegerField(help_text='Soil moisture level (raw sensor value)')),
                ('timestamp', models.DateTimeField(help_text='Time when the measurement was taken')),
            ],
            options={
                'verbose_name_plural': 'Telemetries',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates if device is active (has sent data in last 5 minutes)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(help_text='MAC address of the device (format: XX:XX:XX:XX:XX:XX)', max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Name of the device', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mac_address'], name='devices_dev_mac_add_307aef_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_active'], name='devices_dev_user_id_de7ec5_idx'),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='device',
            field=models.ForeignKey(help_text='Device that sent this telemetry data', on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['timestamp'], name='devices_tel_timesta_bd8d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['device', 'timestamp'], name='devices_tel_device__82fcb2_idx'),
        ),
    ]
