# Generated by Django 5.1.2 on 2025-02-15 20:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_telemetry_alter_device_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSensorLimits',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('temp_min', models.FloatField(help_text='Minimum allowed temperature in Celsius', validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum Temperature')),
                ('temp_max', models.FloatField(help_text='Maximum allowed temperature in Celsius', validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum Temperature')),
                ('humidity_min', models.FloatField(help_text='Minimum allowed humidity in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum Humidity')),
                ('humidity_max', models.FloatField(help_text='Maximum allowed humidity in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum Humidity')),
                ('pressure_min', models.FloatField(help_text='Minimum allowed pressure in hPa', validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(1200)], verbose_name='Minimum Pressure')),
                ('pressure_max', models.FloatField(help_text='Maximum allowed pressure in hPa', validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(1200)], verbose_name='Maximum Pressure')),
                ('soil_moisture_min', models.IntegerField(help_text='Minimum allowed soil moisture value', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1023)], verbose_name='Minimum Soil Moisture')),
                ('soil_moisture_max', models.IntegerField(help_text='Maximum allowed soil moisture value', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1023)], verbose_name='Maximum Soil Moisture')),
                ('device', models.OneToOneField(help_text='Device these limits are for', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_limits', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Sensor Limits',
                'verbose_name_plural': 'Device Sensor Limits',
            },
        ),
    ]
