# Generated by Django 5.1.2 on 2025-02-15 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicesensorlimits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='device',
            field=models.ForeignKey(help_text='Device that sent this telemetry data', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device'),
        ),
    ]
