# Generated by Django 5.1.2 on 2025-02-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_telemetry_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='plant_name',
            field=models.CharField(blank=True, help_text='Name of the plant', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates if device is active (has sent data in last 4 hours)'),
        ),
    ]
