# Generated by Django 5.1.2 on 2025-03-08 19:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_plant_name_alter_device_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('layout', models.JSONField(default=list, help_text='JSON representation of the dashboard layout')),
                ('device', models.OneToOneField(help_text='Device this dashboard layout belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to='devices.device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
