services:
  telemetry:
    build:
      context: .
      dockerfile: telemetry/Dockerfile
    container_name: telemetry
    ports:
      - "8001:50501"
    restart: unless-stopped


#  mosquitto:
#    image: eclipse-mosquitto
#    hostname: mosquitto
#    container_name: mosquitto
#    ports:
#      - "1883:1883"
#      - "9001:9001"
#    restart: unless-stopped
#    volumes:
#      - ./mosquitto:/etc/mosquitto
#      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf



#  mongo:
#    image: mongo
#    restart: always
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#      ME_CONFIG_BASICAUTH: false
