services:
  docs:
    image: plantigo_local_docs
    container_name: plantigo_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./plantigo:/app/plantigo:z
    ports:
      - '9000:9000'
    command: /start-docs
