services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - gateway/.env
    depends_on:
      - devices
    networks:
      - plantigo_network

  devices:
    build:
      context: .
      dockerfile: devices/Dockerfile
    container_name: devices
    ports:
      - "8002:50051"
    restart: unless-stopped
    env_file:
      - devices/.env
    networks:
      - plantigo_network

  telemetry:
    build:
      context: .
      dockerfile: telemetry/Dockerfile
    container_name: telemetry
    ports:
      - "8001:50051"
    restart: unless-stopped
    env_file:
      - telemetry/.env
    networks:
      - plantigo_network

networks:
  plantigo_network:
    driver: bridge
