# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\x1a\x1bgoogle/protobuf/empty.proto\"C\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06groups\x18\x04 \x03(\x05\"\x11\n\x0fUserListRequest\"!\n\x13UserRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xf6\x01\n\x0eUserController\x12/\n\x04List\x12\x16.users.UserListRequest\x1a\x0b.users.User\"\x00\x30\x01\x12$\n\x06\x43reate\x12\x0b.users.User\x1a\x0b.users.User\"\x00\x12\x35\n\x08Retrieve\x12\x1a.users.UserRetrieveRequest\x1a\x0b.users.User\"\x00\x12$\n\x06Update\x12\x0b.users.User\x1a\x0b.users.User\"\x00\x12\x30\n\x07\x44\x65stroy\x12\x0b.users.User\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=51
  _globals['_USER']._serialized_end=118
  _globals['_USERLISTREQUEST']._serialized_start=120
  _globals['_USERLISTREQUEST']._serialized_end=137
  _globals['_USERRETRIEVEREQUEST']._serialized_start=139
  _globals['_USERRETRIEVEREQUEST']._serialized_end=172
  _globals['_USERCONTROLLER']._serialized_start=175
  _globals['_USERCONTROLLER']._serialized_end=421
# @@protoc_insertion_point(module_scope)
