# Generated by Django 5.1.2 on 2025-01-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_customuser_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('google', 'Google'), ('apple', 'Apple')], default='custom', help_text='Specifies the authentication method for the user.', max_length=10),
        ),
    ]
