# Generated by Django 5.1.2 on 2025-01-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_customuser_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
