# Generated by Django 5.1.2 on 2025-01-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_customuser_full_name_customuser_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
