# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dispatcher/dispatcher.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'dispatcher/dispatcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64ispatcher/dispatcher.proto\x12\ndispatcher\"\x90\x01\n\nDeviceData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bmac_address\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x10\n\x08humidity\x18\x04 \x01(\x02\x12\x10\n\x08pressure\x18\x05 \x01(\x02\x12\x15\n\rsoil_moisture\x18\x06 \x01(\x02\x12\x11\n\ttimestamp\x18\x07 \x01(\t\"9\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"M\n\x10TimeRangeRequest\x12\x13\n\x0bmac_address\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\t\"K\n\x0e\x41verageRequest\x12\x13\n\x0bmac_address\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\t\"a\n\x0f\x41verageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0f\x61vg_temperature\x18\x03 \x01(\x02\x12\x14\n\x0c\x61vg_humidity\x18\x04 \x01(\x02\"(\n\x11LastRecordRequest\x12\x13\n\x0bmac_address\x18\x01 \x01(\t\"b\n\x12LastRecordResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12+\n\x0blast_record\x18\x03 \x01(\x0b\x32\x16.dispatcher.DeviceData2\xaf\x02\n\nDispatcher\x12>\n\x0eSendDeviceData\x12\x16.dispatcher.DeviceData\x1a\x14.dispatcher.Response\x12\x46\n\x10GetDataForPeriod\x12\x1c.dispatcher.TimeRangeRequest\x1a\x14.dispatcher.Response\x12I\n\x0eGetAverageData\x12\x1a.dispatcher.AverageRequest\x1a\x1b.dispatcher.AverageResponse\x12N\n\rGetLastRecord\x12\x1d.dispatcher.LastRecordRequest\x1a\x1e.dispatcher.LastRecordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatcher.dispatcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEDATA']._serialized_start=44
  _globals['_DEVICEDATA']._serialized_end=188
  _globals['_RESPONSE']._serialized_start=190
  _globals['_RESPONSE']._serialized_end=247
  _globals['_TIMERANGEREQUEST']._serialized_start=249
  _globals['_TIMERANGEREQUEST']._serialized_end=326
  _globals['_AVERAGEREQUEST']._serialized_start=328
  _globals['_AVERAGEREQUEST']._serialized_end=403
  _globals['_AVERAGERESPONSE']._serialized_start=405
  _globals['_AVERAGERESPONSE']._serialized_end=502
  _globals['_LASTRECORDREQUEST']._serialized_start=504
  _globals['_LASTRECORDREQUEST']._serialized_end=544
  _globals['_LASTRECORDRESPONSE']._serialized_start=546
  _globals['_LASTRECORDRESPONSE']._serialized_end=644
  _globals['_DISPATCHER']._serialized_start=647
  _globals['_DISPATCHER']._serialized_end=950
# @@protoc_insertion_point(module_scope)
